repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: "4.0.1"
  hooks:
  - id: flake8
    additional_dependencies:
    - flake8-bugbear
- repo: https://github.com/psf/black
  rev: "22.3.0"
  hooks:
  - id: black
- repo: https://github.com/PyCQA/isort
  rev: "5.10.1"
  hooks:
  - id: isort
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: "v0.942"
  hooks:
  - id: mypy
    args:
    - --ignore-missing-imports
    - --follow-imports=silent
    additional_dependencies:
    - types-all
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.1.0 # Use the ref you want to point at
  hooks:
  - id: trailing-whitespace